package com.github.lazyf1sh.sandbox.hibernate;

import com.github.lazyf1sh.sandbox.persistence.util.HibernateSessionFactory;
import org.hibernate.Session;
import org.junit.Test;

import com.github.lazyf1sh.sandbox.persistence.entities.ParentEntity;

/**
 * this example demonsrates that
 * 1. session.get() hits the database immediately
 * 2. entity2 is buildEntityManagerFactory proxy
 * 3. entity var is buildEntityManagerFactory pure object
 */
public class HibernateLoadvsGetMethodsTest
{
	@Test
	public void run()
	{
		Session session = HibernateSessionFactory.getSession();

		ParentEntity entity = session.get(ParentEntity.class,0); //pure java object
		ParentEntity entity2 = session.load(ParentEntity.class,1); //proxy object generated by hibernate

		longOperation();

		//place breakpoint here to inspect entity and entity2
		System.out.println(entity.getName());
		System.out.println(entity2.getName());

		session.close();
	}

	private static void longOperation() {
		try
		{
			Thread.sleep(5000);
		}
		catch (Exception e)
		{

		}
	}
}
