DROP TABLE CHILDTABLE;
DROP TABLE PARENTTABLE;

CREATE TABLE PARENTTABLE
(
	PARENTTABLE_KEY integer,
	PARENTTABLE_NAME VARCHAR2(255)
);

ALTER TABLE PARENTTABLE ADD CONSTRAINT PK_PARENTTABLE_KEY PRIMARY KEY (PARENTTABLE_KEY);

CREATE TABLE CHILDTABLE
(
	CHILDTABLE_KEY integer,
	CHILDTABLE_NAME VARCHAR(255),
	CHILDTABLE_PARENT_KEY integer
);

ALTER TABLE CHILDTABLE ADD CONSTRAINT PK_CHILDTABLE_KEY PRIMARY KEY (CHILDTABLE_KEY);
ALTER TABLE CHILDTABLE ADD CONSTRAINT FK_CHILDTABLE_PARENT FOREIGN KEY (CHILDTABLE_PARENT_KEY) REFERENCES PARENTTABLE(PARENTTABLE_KEY);

INSERT INTO PARENTTABLE VALUES (0, 'Parent String 01');
INSERT INTO PARENTTABLE VALUES (1, 'Parent String 02');
INSERT INTO PARENTTABLE VALUES (2, 'Parent String 03');
INSERT INTO PARENTTABLE VALUES (3, 'Parent String 04');

INSERT INTO CHILDTABLE VALUES (0, 'Child String 01', 0);
INSERT INTO CHILDTABLE VALUES (1, 'Child String 02', 1);
INSERT INTO CHILDTABLE VALUES (2, 'Child String 03', 2);
INSERT INTO CHILDTABLE VALUES (3, 'Child String 04', 3);
